import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card"
import {
  type ClassTrees,
  type TalentNode,
  type TalentTab,
  getClassTrees,
  isDatasetEmpty,
  tabPointsSpent,
} from "@/lib/talent-trees"
import { CLASS_COLORS, CLASS_NAMES } from "@/lib/wow-character-enums"
import { SPEC_BACKGROUNDS } from "@/lib/talent-spec-backgrounds"
import { cn } from "@/lib/utils"

/**
 * Talent tree view — three side-by-side spec trees with their talents
 * rendered at their canonical (row, col) positions, just like the
 * in-game talent UI.
 *
 * Consumer feeds:
 *   - `classId`             — picks which class's trees to show
 *   - `pointsByTalentId`    — map of Talent.dbc id → current rank
 *   - `totalPointsAvailable` — for the "Points left: N" header
 *                             (typically `max(0, level - 9)`)
 *
 * The dataset (positions, names, icons) comes from the bundled
 * talent-trees.json, generated by the Rust extractor. When the dataset
 * is empty (extractor hasn't been run), we render an inline prompt
 * pointing the user at Player Bots → Settings → Build talent trees.
 *
 * Visual rules from the in-game tree:
 *   - Talents with rank > 0 render in full color with a gold border
 *   - Untaken talents desaturate (grayscale + dim)
 *   - Bottom-right "X / Y" badge per slot
 *   - Hover shows name + rank + raw description
 *
 * Out of scope for v1:
 *   - Prereq arrows between dependent talents
 *   - $s1/$s2 description template substitution
 *   - Click-to-spend interaction (this is a viewer, not an editor)
 */

const ICON_CDN = "https://wow.zamimg.com/images/wow/icons/large"

export interface TalentTreeProps {
  classId: number
  pointsByTalentId: Record<number, number>
  totalPointsAvailable: number
  /** Optional max grid columns to align the three trees; defaults to 4. */
  gridColumns?: number
}

export function TalentTree({
  classId,
  pointsByTalentId,
  totalPointsAvailable,
  gridColumns = 4,
}: TalentTreeProps) {
  const trees = getClassTrees(classId)
  if (!trees || isDatasetEmpty()) {
    return <EmptyDatasetPrompt />
  }
  return (
    <TalentTreeBody
      trees={trees}
      pointsByTalentId={pointsByTalentId}
      totalPointsAvailable={totalPointsAvailable}
      gridColumns={gridColumns}
    />
  )
}

function TalentTreeBody({
  trees,
  pointsByTalentId,
  totalPointsAvailable,
  gridColumns,
}: {
  trees: ClassTrees
  pointsByTalentId: Record<number, number>
  totalPointsAvailable: number
  gridColumns: number
}) {
  const perTab = trees.tabs.map((t) => tabPointsSpent(t, pointsByTalentId))
  const spent = perTab.reduce((a, b) => a + b, 0)
  const left = Math.max(0, totalPointsAvailable - spent)
  const className = CLASS_NAMES[trees.classId] ?? `Class ${trees.classId}`
  const classColor = CLASS_COLORS[trees.classId] ?? "text-foreground"

  return (
    <div className="overflow-hidden rounded-md border border-border bg-card">
      {/* Top header — class name + tree distribution + points left */}
      <div className="flex items-center justify-between gap-3 border-b border-border bg-muted/40 px-3 py-2 text-sm">
        <div className="flex items-baseline gap-2">
          <span className={cn("font-semibold", classColor)}>{className}:</span>
          <span className="font-mono text-xs text-muted-foreground">
            {perTab.join(" / ")}
          </span>
        </div>
        <div className="text-xs text-muted-foreground">
          Points left:{" "}
          <span className="font-mono font-semibold text-foreground">
            {left}
          </span>
        </div>
      </div>

      {/* Three-column tree body */}
      <div className="grid grid-cols-3 gap-0">
        {trees.tabs.map((tab, i) => (
          <TreeColumn
            key={tab.tabId}
            tab={tab}
            classId={trees.classId}
            pointsSpent={perTab[i]}
            pointsByTalentId={pointsByTalentId}
            gridColumns={gridColumns}
          />
        ))}
      </div>
    </div>
  )
}

// ── Column ─────────────────────────────────────────────────────────────

function TreeColumn({
  tab,
  classId,
  pointsSpent,
  pointsByTalentId,
  gridColumns,
}: {
  tab: TalentTab
  classId: number
  pointsSpent: number
  pointsByTalentId: Record<number, number>
  gridColumns: number
}) {
  const cols = Math.max(gridColumns, tab.maxCol + 1)
  const rows = tab.maxRow + 1
  const background = SPEC_BACKGROUNDS[tab.tabId]

  return (
    <div className="relative flex flex-col bg-stone-900">
      {/* Spec background art (Wowhead), keyed by tabId. A darkening
          overlay sits on top so the talent icons stay readable; the
          header/grid render above both via z-10. */}
      {background && (
        <>
          <div
            className="pointer-events-none absolute inset-0 bg-cover bg-top opacity-40"
            style={{ backgroundImage: `url(${background})` }}
          />
          <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/40 via-black/55 to-stone-950/85" />
        </>
      )}

      {/* Tree header — name + crest + X/71. Sized to match the in-game
          tree header proportions (icon ~28px, name 14px, points 12px). */}
      <div className="relative z-10 flex items-center justify-between gap-2 border-b border-border/60 bg-black/30 px-3 py-2">
        <div className="flex items-center gap-2 min-w-0">
          {tab.iconName && (
            <img
              src={`${ICON_CDN}/${tab.iconName}.jpg`}
              alt={tab.name}
              className="size-7 rounded shrink-0"
              draggable={false}
            />
          )}
          <span className="truncate text-sm font-semibold text-foreground/90">
            {tab.name}
          </span>
        </div>
        <span className="font-mono text-xs text-foreground/70">
          {pointsSpent} / 71
        </span>
      </div>

      {/* Grid — talents placed by (row, col). Empty cells are real
          empty space, just like the in-game tree. */}
      <div
        className="relative z-10 grid gap-1.5 p-2"
        style={{
          gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))`,
          gridTemplateRows: `repeat(${rows}, auto)`,
        }}
      >
        {tab.talents.map((talent) => (
          <TalentSlot
            key={talent.id}
            talent={talent}
            rank={pointsByTalentId[talent.id] ?? 0}
            classId={classId}
          />
        ))}
      </div>
    </div>
  )
}

// ── Slot ───────────────────────────────────────────────────────────────

function TalentSlot({
  talent,
  rank,
  classId,
}: {
  talent: TalentNode
  rank: number
  classId: number
}) {
  const taken = rank > 0
  return (
    <HoverCard openDelay={150} closeDelay={80}>
      <HoverCardTrigger asChild>
        <div
          // Explicit grid placement keeps the slot at its canonical
          // (row, col) regardless of iteration order.
          style={{
            gridColumn: talent.col + 1,
            gridRow: talent.row + 1,
          }}
          className={cn(
            "relative aspect-square overflow-hidden rounded border-2 transition-all",
            taken
              ? "border-amber-400 shadow-[0_0_4px_rgba(251,191,36,0.5)]"
              : "border-stone-700/80"
          )}
        >
          {talent.iconName && (
            <img
              src={`${ICON_CDN}/${talent.iconName}.jpg`}
              alt={talent.name}
              className={cn(
                "size-full object-cover transition-all",
                taken ? "" : "brightness-50 grayscale"
              )}
              draggable={false}
            />
          )}
          <span
            className={cn(
              "absolute bottom-0 right-0 rounded-tl bg-black/85 px-1 py-0.5 font-mono text-[11px] font-semibold leading-none",
              taken ? "text-amber-300" : "text-foreground/60"
            )}
          >
            {rank}/{talent.maxRank}
          </span>
        </div>
      </HoverCardTrigger>
      {/* Wowhead-style chrome — mirrors the ItemTooltip's dark frame
          (bg-[#070712], silver border, beveled inner shadow). Talent
          coloration uses gold name + green/yellow description to
          match Wowhead's talent calc tooltips. */}
      <HoverCardContent
        side="top"
        align="center"
        className={cn(
          "w-[300px] rounded-md border border-[#9a9aaa]/70 bg-[#070712]/95 p-3 text-[12.5px] leading-snug text-white backdrop-blur",
          "shadow-[inset_0_0_0_1px_rgba(0,0,0,0.7),0_8px_24px_rgba(0,0,0,0.7)]"
        )}
      >
        <TalentTooltipBody talent={talent} rank={rank} classId={classId} />
      </HoverCardContent>
    </HoverCard>
  )
}

function TalentTooltipBody({
  talent,
  rank,
  classId,
}: {
  talent: TalentNode
  rank: number
  classId: number
}) {
  const className = CLASS_NAMES[classId] ?? ""
  // Display rank: when 0 (untaken), show "Rank 1/N" as the rank the
  // first point would learn (matches WoW's in-game tooltip behavior).
  const displayRank = rank > 0 ? rank : 1
  return (
    <div className="space-y-1.5">
      {/* Title — gold/amber, the WoW canonical talent name color. */}
      <div className="text-[13px] font-semibold leading-tight text-[#ffd100]">
        {talent.name}
      </div>
      {/* Sub-line: class + rank. Wowhead shows "Talent" + "Requires
          Hunter" on separate lines; we collapse for vertical density
          since talents only exist on one class anyway. */}
      <div className="text-[11px] leading-tight text-zinc-300">
        {className ? `Requires ${className} · ` : ""}Rank {displayRank} /{" "}
        {talent.maxRank}
      </div>
      {/* Description — the in-game pale yellow body text. Spell
          placeholder substitution ($s1/$s2 → numeric values) is a
          future-work item; for now the raw template is shown so the
          intent of the talent is still legible. */}
      {talent.description && (
        <div className="whitespace-pre-line pt-1 text-[12px] leading-snug text-[#ffd100]/95">
          {talent.description}
        </div>
      )}
    </div>
  )
}

// ── Empty state ────────────────────────────────────────────────────────

function EmptyDatasetPrompt() {
  return (
    <div className="rounded-md border border-dashed border-border bg-muted/20 p-4 text-xs text-muted-foreground">
      <div className="space-y-1">
        <div className="font-semibold text-foreground">
          Talent trees not extracted yet
        </div>
        <p>
          Connect your WoW client on the dashboard, then run{" "}
          <span className="font-mono">
            Player Bots → Settings → Build talent trees
          </span>{" "}
          to populate this view.
        </p>
      </div>
    </div>
  )
}
