import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  type ClassTrees,
  type TalentNode,
  type TalentTab,
  getClassTrees,
  isDatasetEmpty,
  tabPointsSpent,
} from "@/lib/talent-trees"
import { CLASS_COLORS, CLASS_NAMES } from "@/lib/wow-character-enums"
import { cn } from "@/lib/utils"

/**
 * Talent tree view — three side-by-side spec trees with their talents
 * rendered at their canonical (row, col) positions, just like the
 * in-game talent UI.
 *
 * Consumer feeds:
 *   - `classId`             — picks which class's trees to show
 *   - `pointsByTalentId`    — map of Talent.dbc id → current rank
 *   - `totalPointsAvailable` — for the "Points left: N" header
 *                             (typically `max(0, level - 9)`)
 *
 * The dataset (positions, names, icons) comes from the bundled
 * talent-trees.json, generated by the Rust extractor. When the dataset
 * is empty (extractor hasn't been run), we render an inline prompt
 * pointing the user at Player Bots → Settings → Build talent trees.
 *
 * Visual rules from the in-game tree:
 *   - Talents with rank > 0 render in full color with a gold border
 *   - Untaken talents desaturate (grayscale + dim)
 *   - Bottom-right "X / Y" badge per slot
 *   - Hover shows name + rank + raw description
 *
 * Out of scope for v1:
 *   - Prereq arrows between dependent talents
 *   - $s1/$s2 description template substitution
 *   - Click-to-spend interaction (this is a viewer, not an editor)
 */

const ICON_CDN = "https://wow.zamimg.com/images/wow/icons/large"

export interface TalentTreeProps {
  classId: number
  pointsByTalentId: Record<number, number>
  totalPointsAvailable: number
  /** Optional max grid columns to align the three trees; defaults to 4. */
  gridColumns?: number
}

export function TalentTree({
  classId,
  pointsByTalentId,
  totalPointsAvailable,
  gridColumns = 4,
}: TalentTreeProps) {
  const trees = getClassTrees(classId)
  if (!trees || isDatasetEmpty()) {
    return <EmptyDatasetPrompt />
  }
  return (
    <TalentTreeBody
      trees={trees}
      pointsByTalentId={pointsByTalentId}
      totalPointsAvailable={totalPointsAvailable}
      gridColumns={gridColumns}
    />
  )
}

function TalentTreeBody({
  trees,
  pointsByTalentId,
  totalPointsAvailable,
  gridColumns,
}: {
  trees: ClassTrees
  pointsByTalentId: Record<number, number>
  totalPointsAvailable: number
  gridColumns: number
}) {
  const perTab = trees.tabs.map((t) => tabPointsSpent(t, pointsByTalentId))
  const spent = perTab.reduce((a, b) => a + b, 0)
  const left = Math.max(0, totalPointsAvailable - spent)
  const className = CLASS_NAMES[trees.classId] ?? `Class ${trees.classId}`
  const classColor = CLASS_COLORS[trees.classId] ?? "text-foreground"

  return (
    <div className="overflow-hidden rounded-md border border-border bg-card">
      {/* Top header — class name + tree distribution + points left */}
      <div className="flex items-center justify-between gap-3 border-b border-border bg-muted/40 px-3 py-2 text-sm">
        <div className="flex items-baseline gap-2">
          <span className={cn("font-semibold", classColor)}>{className}:</span>
          <span className="font-mono text-xs text-muted-foreground">
            {perTab.join(" / ")}
          </span>
        </div>
        <div className="text-xs text-muted-foreground">
          Points left:{" "}
          <span className="font-mono font-semibold text-foreground">
            {left}
          </span>
        </div>
      </div>

      {/* Three-column tree body */}
      <div className="grid grid-cols-3 gap-0">
        {trees.tabs.map((tab, i) => (
          <TreeColumn
            key={tab.tabId}
            tab={tab}
            pointsSpent={perTab[i]}
            pointsByTalentId={pointsByTalentId}
            gridColumns={gridColumns}
          />
        ))}
      </div>
    </div>
  )
}

// ── Column ─────────────────────────────────────────────────────────────

const TAB_BACKGROUND_TINTS: Record<number, string> = {
  // (tabIndex 0/1/2) — soft tint per tree for visual differentiation.
  // Real client background art is punted; these gradients evoke the
  // jungle / snow / forest themes Bliz used per tree without ripping
  // the source textures.
  0: "from-emerald-950/60 to-stone-900",
  1: "from-slate-900 to-stone-900",
  2: "from-teal-950/60 to-stone-900",
}

function TreeColumn({
  tab,
  pointsSpent,
  pointsByTalentId,
  gridColumns,
}: {
  tab: TalentTab
  pointsSpent: number
  pointsByTalentId: Record<number, number>
  gridColumns: number
}) {
  const cols = Math.max(gridColumns, tab.maxCol + 1)
  const rows = tab.maxRow + 1

  return (
    <div
      className={cn(
        "flex flex-col bg-gradient-to-b",
        TAB_BACKGROUND_TINTS[tab.tabIndex] ?? "from-stone-900 to-stone-900"
      )}
    >
      {/* Tree header — name + crest + X/71 */}
      <div className="flex items-center justify-between gap-2 border-b border-border/60 bg-black/30 px-2.5 py-1.5">
        <div className="flex items-center gap-1.5 min-w-0">
          {tab.iconName && (
            <img
              src={`${ICON_CDN}/${tab.iconName}.jpg`}
              alt={tab.name}
              className="size-5 rounded shrink-0"
              draggable={false}
            />
          )}
          <span className="truncate text-xs font-semibold text-foreground/90">
            {tab.name}
          </span>
        </div>
        <span className="font-mono text-[10px] text-foreground/70">
          {pointsSpent} / 71
        </span>
      </div>

      {/* Grid — talents placed by (row, col). Empty cells are real
          empty space, just like the in-game tree. */}
      <div
        className="grid gap-1.5 p-2"
        style={{
          gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))`,
          gridTemplateRows: `repeat(${rows}, auto)`,
        }}
      >
        {tab.talents.map((talent) => (
          <TalentSlot
            key={talent.id}
            talent={talent}
            rank={pointsByTalentId[talent.id] ?? 0}
          />
        ))}
      </div>
    </div>
  )
}

// ── Slot ───────────────────────────────────────────────────────────────

function TalentSlot({ talent, rank }: { talent: TalentNode; rank: number }) {
  const taken = rank > 0
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <div
          // Explicit grid placement keeps the slot at its canonical
          // (row, col) regardless of iteration order.
          style={{
            gridColumn: talent.col + 1,
            gridRow: talent.row + 1,
          }}
          className={cn(
            "relative aspect-square overflow-hidden rounded border-2 transition-all",
            taken
              ? "border-amber-400 shadow-[0_0_4px_rgba(251,191,36,0.5)]"
              : "border-stone-700/80"
          )}
        >
          {talent.iconName && (
            <img
              src={`${ICON_CDN}/${talent.iconName}.jpg`}
              alt={talent.name}
              className={cn(
                "size-full object-cover transition-all",
                taken
                  ? ""
                  : "brightness-50 grayscale"
              )}
              draggable={false}
            />
          )}
          <span
            className={cn(
              "absolute bottom-0 right-0 rounded-tl bg-black/85 px-1 py-px font-mono text-[9px] leading-tight",
              taken ? "text-amber-300" : "text-foreground/60"
            )}
          >
            {rank}/{talent.maxRank}
          </span>
        </div>
      </TooltipTrigger>
      <TooltipContent side="top" className="max-w-xs space-y-1 text-xs">
        <div className="flex items-baseline justify-between gap-3">
          <span className="font-semibold">{talent.name}</span>
          <span className="font-mono text-[10px] text-foreground/70">
            {rank}/{talent.maxRank}
          </span>
        </div>
        {talent.description && (
          <div className="text-[11px] leading-snug text-foreground/80">
            {talent.description}
          </div>
        )}
      </TooltipContent>
    </Tooltip>
  )
}

// ── Empty state ────────────────────────────────────────────────────────

function EmptyDatasetPrompt() {
  return (
    <div className="rounded-md border border-dashed border-border bg-muted/20 p-4 text-xs text-muted-foreground">
      <div className="space-y-1">
        <div className="font-semibold text-foreground">
          Talent trees not extracted yet
        </div>
        <p>
          Connect your WoW client on the dashboard, then run{" "}
          <span className="font-mono">
            Player Bots → Settings → Build talent trees
          </span>{" "}
          to populate this view.
        </p>
      </div>
    </div>
  )
}
